repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: d2bd9cd497c81622c3f5774b336ab451691f1c36
    hooks:
      - id: check-yaml
        exclude: ^(conda\.recipe/meta\.yaml|conda_build/templates/.*\.yaml|docs/click/meta\.yaml|conda/meta\.yaml|conda/construct.yaml|.*\.pic\.yml|conda/constructor/Miniforge3/construct.yaml)
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 1b028cc9d99c2c2e82f9b727742539173a92a373
    hooks:
      - id: black
        # exclude: '^gdsfactory/samples/notebooks/|^docs/notebooks/'

  - repo: https://github.com/codespell-project/codespell
    rev: 38bc4a97f6e22827e86526148efa38f1044a97f8
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "6c0ceaccffa1ebb1db1ea1a6d7289b50d29bfce2"
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.10.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]

  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.1.0
    hooks:
      - id: j2lint
        args: [--ignore, jinja-statements-delimiter, jinja-statements-indentation, --]
